name: Data Collection & Sync

on:
  workflow_dispatch:
  
  # schedule:
  #   - cron: '59 8 * * *' # Run everyday at 06:08

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
        with:
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r actions_requirements.txt
          
      - name: execute py script # run main.py
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          python wallet_accts.py 
          python acct_df.py 
      
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Synced data from API'
        
